### ISSUE TITLE
No match asgardcms/core-module ~2.0

### ISSUE THREAD

**Issue by JKChen** [AsgardCms/Notification#7]
Is there a plan to update this awesome module to match `asgardcms/core-module ~2.0`?

**Comment by nWidart** [comment]
I still need to do this yes. When I have time. Feel free to help though of course.

Btw, it's not asgardcms/core, but `idavoll/core-module` now.

**Comment by JKChen** [comment]
Yeah,you're right.
Looking forward to your updates.

**Comment by JKChen** [comment]
I found that just run `composer require asgardcms/notification-module ~2.0` can avoid this issue.

**Comment by nWidart** [comment]
Hm that was a WIP, is it working for you in asgard 2.0? If so that'll make the migration easy. 😄

**Comment by JKChen** [comment]
Yes,it works in asgard 2.0.

**Comment by nWidart** [comment]
This has been tagged, also for version 3. 👍
